#Shimeji-ee Configuration Options
#Thu Sep 03 15:02:25 CST 2026
ActiveShimeji=Eviling/KuroShimeji/Neuron/Shimeji
AlwaysShowInformationScreen=false
AlwaysShowShimejiChooser=false
Background=\#FF9999
BackgroundImage=
BackgroundMode=centre
Breeding=true
Environment=generic
Filter=bicubic
InteractiveWindows=Chat/Notepad/Friends/Windows Live Messenger
InteractiveWindowsBlacklist=
Language=zh-CN
MenuDPI=192
Opacity=1.0
Scaling=1.2
WindowSize=600x500
