#FlatLaf Theme Configuration
#Thu Sep 03 14:57:27 CST 2026
BlackColour=\#FF9999
FontName=Dialog-0-0-0-0-0
FontSize=130023424
FontStyle=0
MenuOpacity=204
PrimaryColour1=\#FF9999
PrimaryColour2=\#FF9999
PrimaryColour3=\#FF9966
SecondaryColour1=\#FFCCCC
SecondaryColour2=\#FF99CC
SecondaryColour3=\#FFCCCC
WhiteColour=\#FF9999
